package com.dianwoba.dispatch.sender.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class AppDep implements Serializable {
    private Long id;

    private String appName;

    private String ownersDepId;

    private String ownersPhone;

    private String developersDepId;

    private String developersPhone;

    private Integer depId;

    private Integer manualDepId;

    private Date depPlatModifyTime;

    private Date createTime;

    private Date modifyTime;

    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    public String getOwnersDepId() {
        return ownersDepId;
    }

    public void setOwnersDepId(String ownersDepId) {
        this.ownersDepId = ownersDepId == null ? null : ownersDepId.trim();
    }

    public String getOwnersPhone() {
        return ownersPhone;
    }

    public void setOwnersPhone(String ownersPhone) {
        this.ownersPhone = ownersPhone == null ? null : ownersPhone.trim();
    }

    public String getDevelopersDepId() {
        return developersDepId;
    }

    public void setDevelopersDepId(String developersDepId) {
        this.developersDepId = developersDepId == null ? null : developersDepId.trim();
    }

    public String getDevelopersPhone() {
        return developersPhone;
    }

    public void setDevelopersPhone(String developersPhone) {
        this.developersPhone = developersPhone == null ? null : developersPhone.trim();
    }

    public Integer getDepId() {
        return depId;
    }

    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    public Integer getManualDepId() {
        return manualDepId;
    }

    public void setManualDepId(Integer manualDepId) {
        this.manualDepId = manualDepId;
    }

    public Date getDepPlatModifyTime() {
        return depPlatModifyTime;
    }

    public void setDepPlatModifyTime(Date depPlatModifyTime) {
        this.depPlatModifyTime = depPlatModifyTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table app_dep
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        appName("app_name", "appName", "VARCHAR"),
        ownersDepId("owners_dep_id", "ownersDepId", "VARCHAR"),
        ownersPhone("owners_phone", "ownersPhone", "VARCHAR"),
        developersDepId("developers_dep_id", "developersDepId", "VARCHAR"),
        developersPhone("developers_phone", "developersPhone", "VARCHAR"),
        depId("dep_id", "depId", "INTEGER"),
        manualDepId("manual_dep_id", "manualDepId", "INTEGER"),
        depPlatModifyTime("dep_plat_modify_time", "depPlatModifyTime", "TIMESTAMP"),
        createTime("create_time", "createTime", "TIMESTAMP"),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_dep
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }
    }
}