package com.dianwoba.dispatch.sender.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class MessageSend implements Serializable {
    private Long id;

    private String clusterId;

    private Long groupId;

    private String appCode;

    private String ips;

    private String exceptionType;

    private String digest;

    private String msg;

    private Byte level;

    private Date startTm;

    private Date endTm;

    private Integer count;

    private String atWho;

    private Date insertTm;

    private Byte status;

    private Date sendTm;

    private String robotErrorCode;

    private String robotErrorMsg;

    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClusterId() {
        return clusterId;
    }

    public void setClusterId(String clusterId) {
        this.clusterId = clusterId == null ? null : clusterId.trim();
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getAppCode() {
        return appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    public String getIps() {
        return ips;
    }

    public void setIps(String ips) {
        this.ips = ips == null ? null : ips.trim();
    }

    public String getExceptionType() {
        return exceptionType;
    }

    public void setExceptionType(String exceptionType) {
        this.exceptionType = exceptionType == null ? null : exceptionType.trim();
    }

    public String getDigest() {
        return digest;
    }

    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    public Byte getLevel() {
        return level;
    }

    public void setLevel(Byte level) {
        this.level = level;
    }

    public Date getStartTm() {
        return startTm;
    }

    public void setStartTm(Date startTm) {
        this.startTm = startTm;
    }

    public Date getEndTm() {
        return endTm;
    }

    public void setEndTm(Date endTm) {
        this.endTm = endTm;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getAtWho() {
        return atWho;
    }

    public void setAtWho(String atWho) {
        this.atWho = atWho == null ? null : atWho.trim();
    }

    public Date getInsertTm() {
        return insertTm;
    }

    public void setInsertTm(Date insertTm) {
        this.insertTm = insertTm;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Date getSendTm() {
        return sendTm;
    }

    public void setSendTm(Date sendTm) {
        this.sendTm = sendTm;
    }

    public String getRobotErrorCode() {
        return robotErrorCode;
    }

    public void setRobotErrorCode(String robotErrorCode) {
        this.robotErrorCode = robotErrorCode == null ? null : robotErrorCode.trim();
    }

    public String getRobotErrorMsg() {
        return robotErrorMsg;
    }

    public void setRobotErrorMsg(String robotErrorMsg) {
        this.robotErrorMsg = robotErrorMsg == null ? null : robotErrorMsg.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT"),
        clusterId("cluster_id", "clusterId", "VARCHAR"),
        groupId("group_id", "groupId", "BIGINT"),
        appCode("app_code", "appCode", "VARCHAR"),
        ips("ips", "ips", "VARCHAR"),
        exceptionType("exception_type", "exceptionType", "VARCHAR"),
        digest("digest", "digest", "VARCHAR"),
        msg("msg", "msg", "VARCHAR"),
        level("level", "level", "TINYINT"),
        startTm("start_tm", "startTm", "TIMESTAMP"),
        endTm("end_tm", "endTm", "TIMESTAMP"),
        count("count", "count", "INTEGER"),
        atWho("at_who", "atWho", "VARCHAR"),
        insertTm("insert_tm", "insertTm", "TIMESTAMP"),
        status("status", "status", "TINYINT"),
        sendTm("send_tm", "sendTm", "TIMESTAMP"),
        robotErrorCode("robot_error_code", "robotErrorCode", "VARCHAR"),
        robotErrorMsg("robot_error_msg", "robotErrorMsg", "VARCHAR");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }
    }
}