package com.dianwoba.dispatch.sender.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageSendExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public MessageSendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public MessageSendExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public MessageSendExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public MessageSendExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public MessageSendExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public MessageSendExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppDepIsNull() {
            addCriterion("app_dep is null");
            return (Criteria) this;
        }

        public Criteria andAppDepIsNotNull() {
            addCriterion("app_dep is not null");
            return (Criteria) this;
        }

        public Criteria andAppDepEqualTo(String value) {
            addCriterion("app_dep =", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepNotEqualTo(String value) {
            addCriterion("app_dep <>", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepGreaterThan(String value) {
            addCriterion("app_dep >", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepGreaterThanOrEqualTo(String value) {
            addCriterion("app_dep >=", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepLessThan(String value) {
            addCriterion("app_dep <", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepLessThanOrEqualTo(String value) {
            addCriterion("app_dep <=", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepLike(String value) {
            addCriterion("app_dep like", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepNotLike(String value) {
            addCriterion("app_dep not like", value, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepIn(List<String> values) {
            addCriterion("app_dep in", values, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepNotIn(List<String> values) {
            addCriterion("app_dep not in", values, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepBetween(String value1, String value2) {
            addCriterion("app_dep between", value1, value2, "appDep");
            return (Criteria) this;
        }

        public Criteria andAppDepNotBetween(String value1, String value2) {
            addCriterion("app_dep not between", value1, value2, "appDep");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Long value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Long value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Long value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Long value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Long> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Long> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Long value1, Long value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("app_name is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("app_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("app_name =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("app_name <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("app_name >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_name >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("app_name <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("app_name <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("app_name like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("app_name not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("app_name in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("app_name not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("app_name between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("app_name not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andIpsIsNull() {
            addCriterion("ips is null");
            return (Criteria) this;
        }

        public Criteria andIpsIsNotNull() {
            addCriterion("ips is not null");
            return (Criteria) this;
        }

        public Criteria andIpsEqualTo(String value) {
            addCriterion("ips =", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotEqualTo(String value) {
            addCriterion("ips <>", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsGreaterThan(String value) {
            addCriterion("ips >", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsGreaterThanOrEqualTo(String value) {
            addCriterion("ips >=", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLessThan(String value) {
            addCriterion("ips <", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLessThanOrEqualTo(String value) {
            addCriterion("ips <=", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsLike(String value) {
            addCriterion("ips like", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotLike(String value) {
            addCriterion("ips not like", value, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsIn(List<String> values) {
            addCriterion("ips in", values, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotIn(List<String> values) {
            addCriterion("ips not in", values, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsBetween(String value1, String value2) {
            addCriterion("ips between", value1, value2, "ips");
            return (Criteria) this;
        }

        public Criteria andIpsNotBetween(String value1, String value2) {
            addCriterion("ips not between", value1, value2, "ips");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeIsNull() {
            addCriterion("exception_type is null");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeIsNotNull() {
            addCriterion("exception_type is not null");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeEqualTo(String value) {
            addCriterion("exception_type =", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeNotEqualTo(String value) {
            addCriterion("exception_type <>", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeGreaterThan(String value) {
            addCriterion("exception_type >", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("exception_type >=", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeLessThan(String value) {
            addCriterion("exception_type <", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeLessThanOrEqualTo(String value) {
            addCriterion("exception_type <=", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeLike(String value) {
            addCriterion("exception_type like", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeNotLike(String value) {
            addCriterion("exception_type not like", value, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeIn(List<String> values) {
            addCriterion("exception_type in", values, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeNotIn(List<String> values) {
            addCriterion("exception_type not in", values, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeBetween(String value1, String value2) {
            addCriterion("exception_type between", value1, value2, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andExceptionTypeNotBetween(String value1, String value2) {
            addCriterion("exception_type not between", value1, value2, "exceptionType");
            return (Criteria) this;
        }

        public Criteria andDigestIsNull() {
            addCriterion("digest is null");
            return (Criteria) this;
        }

        public Criteria andDigestIsNotNull() {
            addCriterion("digest is not null");
            return (Criteria) this;
        }

        public Criteria andDigestEqualTo(String value) {
            addCriterion("digest =", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotEqualTo(String value) {
            addCriterion("digest <>", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThan(String value) {
            addCriterion("digest >", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThanOrEqualTo(String value) {
            addCriterion("digest >=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThan(String value) {
            addCriterion("digest <", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThanOrEqualTo(String value) {
            addCriterion("digest <=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLike(String value) {
            addCriterion("digest like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotLike(String value) {
            addCriterion("digest not like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestIn(List<String> values) {
            addCriterion("digest in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotIn(List<String> values) {
            addCriterion("digest not in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestBetween(String value1, String value2) {
            addCriterion("digest between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotBetween(String value1, String value2) {
            addCriterion("digest not between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("msg is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("msg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("msg =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("msg <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("msg >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("msg >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("msg <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("msg <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("msg like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("msg not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("msg in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("msg not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("msg between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("msg not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Byte value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Byte value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Byte value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Byte value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Byte value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Byte> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Byte> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Byte value1, Byte value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andStartTmIsNull() {
            addCriterion("start_tm is null");
            return (Criteria) this;
        }

        public Criteria andStartTmIsNotNull() {
            addCriterion("start_tm is not null");
            return (Criteria) this;
        }

        public Criteria andStartTmEqualTo(Date value) {
            addCriterion("start_tm =", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmNotEqualTo(Date value) {
            addCriterion("start_tm <>", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmGreaterThan(Date value) {
            addCriterion("start_tm >", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmGreaterThanOrEqualTo(Date value) {
            addCriterion("start_tm >=", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmLessThan(Date value) {
            addCriterion("start_tm <", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmLessThanOrEqualTo(Date value) {
            addCriterion("start_tm <=", value, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmIn(List<Date> values) {
            addCriterion("start_tm in", values, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmNotIn(List<Date> values) {
            addCriterion("start_tm not in", values, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmBetween(Date value1, Date value2) {
            addCriterion("start_tm between", value1, value2, "startTm");
            return (Criteria) this;
        }

        public Criteria andStartTmNotBetween(Date value1, Date value2) {
            addCriterion("start_tm not between", value1, value2, "startTm");
            return (Criteria) this;
        }

        public Criteria andEndTmIsNull() {
            addCriterion("end_tm is null");
            return (Criteria) this;
        }

        public Criteria andEndTmIsNotNull() {
            addCriterion("end_tm is not null");
            return (Criteria) this;
        }

        public Criteria andEndTmEqualTo(Date value) {
            addCriterion("end_tm =", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotEqualTo(Date value) {
            addCriterion("end_tm <>", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmGreaterThan(Date value) {
            addCriterion("end_tm >", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmGreaterThanOrEqualTo(Date value) {
            addCriterion("end_tm >=", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmLessThan(Date value) {
            addCriterion("end_tm <", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmLessThanOrEqualTo(Date value) {
            addCriterion("end_tm <=", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmIn(List<Date> values) {
            addCriterion("end_tm in", values, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotIn(List<Date> values) {
            addCriterion("end_tm not in", values, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmBetween(Date value1, Date value2) {
            addCriterion("end_tm between", value1, value2, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotBetween(Date value1, Date value2) {
            addCriterion("end_tm not between", value1, value2, "endTm");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andAtWhoIsNull() {
            addCriterion("at_who is null");
            return (Criteria) this;
        }

        public Criteria andAtWhoIsNotNull() {
            addCriterion("at_who is not null");
            return (Criteria) this;
        }

        public Criteria andAtWhoEqualTo(String value) {
            addCriterion("at_who =", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoNotEqualTo(String value) {
            addCriterion("at_who <>", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoGreaterThan(String value) {
            addCriterion("at_who >", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoGreaterThanOrEqualTo(String value) {
            addCriterion("at_who >=", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoLessThan(String value) {
            addCriterion("at_who <", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoLessThanOrEqualTo(String value) {
            addCriterion("at_who <=", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoLike(String value) {
            addCriterion("at_who like", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoNotLike(String value) {
            addCriterion("at_who not like", value, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoIn(List<String> values) {
            addCriterion("at_who in", values, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoNotIn(List<String> values) {
            addCriterion("at_who not in", values, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoBetween(String value1, String value2) {
            addCriterion("at_who between", value1, value2, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtWhoNotBetween(String value1, String value2) {
            addCriterion("at_who not between", value1, value2, "atWho");
            return (Criteria) this;
        }

        public Criteria andAtAllIsNull() {
            addCriterion("at_all is null");
            return (Criteria) this;
        }

        public Criteria andAtAllIsNotNull() {
            addCriterion("at_all is not null");
            return (Criteria) this;
        }

        public Criteria andAtAllEqualTo(Boolean value) {
            addCriterion("at_all =", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllNotEqualTo(Boolean value) {
            addCriterion("at_all <>", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllGreaterThan(Boolean value) {
            addCriterion("at_all >", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllGreaterThanOrEqualTo(Boolean value) {
            addCriterion("at_all >=", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllLessThan(Boolean value) {
            addCriterion("at_all <", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllLessThanOrEqualTo(Boolean value) {
            addCriterion("at_all <=", value, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllIn(List<Boolean> values) {
            addCriterion("at_all in", values, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllNotIn(List<Boolean> values) {
            addCriterion("at_all not in", values, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllBetween(Boolean value1, Boolean value2) {
            addCriterion("at_all between", value1, value2, "atAll");
            return (Criteria) this;
        }

        public Criteria andAtAllNotBetween(Boolean value1, Boolean value2) {
            addCriterion("at_all not between", value1, value2, "atAll");
            return (Criteria) this;
        }

        public Criteria andInsertTmIsNull() {
            addCriterion("insert_tm is null");
            return (Criteria) this;
        }

        public Criteria andInsertTmIsNotNull() {
            addCriterion("insert_tm is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTmEqualTo(Date value) {
            addCriterion("insert_tm =", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmNotEqualTo(Date value) {
            addCriterion("insert_tm <>", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmGreaterThan(Date value) {
            addCriterion("insert_tm >", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_tm >=", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmLessThan(Date value) {
            addCriterion("insert_tm <", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmLessThanOrEqualTo(Date value) {
            addCriterion("insert_tm <=", value, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmIn(List<Date> values) {
            addCriterion("insert_tm in", values, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmNotIn(List<Date> values) {
            addCriterion("insert_tm not in", values, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmBetween(Date value1, Date value2) {
            addCriterion("insert_tm between", value1, value2, "insertTm");
            return (Criteria) this;
        }

        public Criteria andInsertTmNotBetween(Date value1, Date value2) {
            addCriterion("insert_tm not between", value1, value2, "insertTm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSendTmIsNull() {
            addCriterion("send_tm is null");
            return (Criteria) this;
        }

        public Criteria andSendTmIsNotNull() {
            addCriterion("send_tm is not null");
            return (Criteria) this;
        }

        public Criteria andSendTmEqualTo(Date value) {
            addCriterion("send_tm =", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmNotEqualTo(Date value) {
            addCriterion("send_tm <>", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmGreaterThan(Date value) {
            addCriterion("send_tm >", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmGreaterThanOrEqualTo(Date value) {
            addCriterion("send_tm >=", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmLessThan(Date value) {
            addCriterion("send_tm <", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmLessThanOrEqualTo(Date value) {
            addCriterion("send_tm <=", value, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmIn(List<Date> values) {
            addCriterion("send_tm in", values, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmNotIn(List<Date> values) {
            addCriterion("send_tm not in", values, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmBetween(Date value1, Date value2) {
            addCriterion("send_tm between", value1, value2, "sendTm");
            return (Criteria) this;
        }

        public Criteria andSendTmNotBetween(Date value1, Date value2) {
            addCriterion("send_tm not between", value1, value2, "sendTm");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeIsNull() {
            addCriterion("robot_error_code is null");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeIsNotNull() {
            addCriterion("robot_error_code is not null");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeEqualTo(String value) {
            addCriterion("robot_error_code =", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeNotEqualTo(String value) {
            addCriterion("robot_error_code <>", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeGreaterThan(String value) {
            addCriterion("robot_error_code >", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("robot_error_code >=", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeLessThan(String value) {
            addCriterion("robot_error_code <", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeLessThanOrEqualTo(String value) {
            addCriterion("robot_error_code <=", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeLike(String value) {
            addCriterion("robot_error_code like", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeNotLike(String value) {
            addCriterion("robot_error_code not like", value, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeIn(List<String> values) {
            addCriterion("robot_error_code in", values, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeNotIn(List<String> values) {
            addCriterion("robot_error_code not in", values, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeBetween(String value1, String value2) {
            addCriterion("robot_error_code between", value1, value2, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorCodeNotBetween(String value1, String value2) {
            addCriterion("robot_error_code not between", value1, value2, "robotErrorCode");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgIsNull() {
            addCriterion("robot_error_msg is null");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgIsNotNull() {
            addCriterion("robot_error_msg is not null");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgEqualTo(String value) {
            addCriterion("robot_error_msg =", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgNotEqualTo(String value) {
            addCriterion("robot_error_msg <>", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgGreaterThan(String value) {
            addCriterion("robot_error_msg >", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgGreaterThanOrEqualTo(String value) {
            addCriterion("robot_error_msg >=", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgLessThan(String value) {
            addCriterion("robot_error_msg <", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgLessThanOrEqualTo(String value) {
            addCriterion("robot_error_msg <=", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgLike(String value) {
            addCriterion("robot_error_msg like", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgNotLike(String value) {
            addCriterion("robot_error_msg not like", value, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgIn(List<String> values) {
            addCriterion("robot_error_msg in", values, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgNotIn(List<String> values) {
            addCriterion("robot_error_msg not in", values, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgBetween(String value1, String value2) {
            addCriterion("robot_error_msg between", value1, value2, "robotErrorMsg");
            return (Criteria) this;
        }

        public Criteria andRobotErrorMsgNotBetween(String value1, String value2) {
            addCriterion("robot_error_msg not between", value1, value2, "robotErrorMsg");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private MessageSendExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(MessageSendExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public MessageSendExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table message_send
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table message_send
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}