package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.AppDep;
import com.dianwoba.dispatch.sender.entity.AppDepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppDepMapper {
    long countByExample(AppDepExample example);

    int deleteByExample(AppDepExample example);

    int deleteByPrimaryKey(Long id);

    int insert(AppDep record);

    int insertSelective(AppDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_dep
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<AppDep> selectByExampleSelective(@Param("example") AppDepExample example, @Param("selective") AppDep.Column ... selective);

    List<AppDep> selectByExample(AppDepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_dep
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AppDep selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") AppDep.Column ... selective);

    AppDep selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") AppDep record, @Param("example") AppDepExample example);

    int updateByExample(@Param("record") AppDep record, @Param("example") AppDepExample example);

    int updateByPrimaryKeySelective(AppDep record);

    int updateByPrimaryKey(AppDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_dep
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AppDep> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_dep
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AppDep> list, @Param("selective") AppDep.Column ... selective);
}