package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.DepInfo;
import com.dianwoba.dispatch.sender.entity.DepInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepInfoMapper {
    long countByExample(DepInfoExample example);

    int deleteByExample(DepInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(DepInfo record);

    int insertSelective(DepInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DepInfo> selectByExampleSelective(@Param("example") DepInfoExample example, @Param("selective") DepInfo.Column ... selective);

    List<DepInfo> selectByExample(DepInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DepInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DepInfo.Column ... selective);

    DepInfo selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") DepInfo record, @Param("example") DepInfoExample example);

    int updateByExample(@Param("record") DepInfo record, @Param("example") DepInfoExample example);

    int updateByPrimaryKeySelective(DepInfo record);

    int updateByPrimaryKey(DepInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DepInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dep_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DepInfo> list, @Param("selective") DepInfo.Column ... selective);
}