package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.DingTokenConfig;
import com.dianwoba.dispatch.sender.entity.DingTokenConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DingTokenConfigMapper {
    long countByExample(DingTokenConfigExample example);

    int deleteByExample(DingTokenConfigExample example);

    int deleteByPrimaryKey(Long id);

    int insert(DingTokenConfig record);

    int insertSelective(DingTokenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_token_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DingTokenConfig> selectByExampleSelective(@Param("example") DingTokenConfigExample example, @Param("selective") DingTokenConfig.Column ... selective);

    List<DingTokenConfig> selectByExample(DingTokenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_token_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DingTokenConfig selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") DingTokenConfig.Column ... selective);

    DingTokenConfig selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") DingTokenConfig record, @Param("example") DingTokenConfigExample example);

    int updateByExample(@Param("record") DingTokenConfig record, @Param("example") DingTokenConfigExample example);

    int updateByPrimaryKeySelective(DingTokenConfig record);

    int updateByPrimaryKey(DingTokenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_token_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DingTokenConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_token_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DingTokenConfig> list, @Param("selective") DingTokenConfig.Column ... selective);
}