package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.DingGroupName;
import com.dianwoba.dispatch.sender.entity.DingGroupNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DingGroupNameMapper {
    long countByExample(DingGroupNameExample example);

    int deleteByExample(DingGroupNameExample example);

    int deleteByPrimaryKey(Long id);

    int insert(DingGroupName record);

    int insertSelective(DingGroupName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_group_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DingGroupName> selectByExampleSelective(@Param("example") DingGroupNameExample example, @Param("selective") DingGroupName.Column ... selective);

    List<DingGroupName> selectByExample(DingGroupNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_group_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DingGroupName selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") DingGroupName.Column ... selective);

    DingGroupName selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") DingGroupName record, @Param("example") DingGroupNameExample example);

    int updateByExample(@Param("record") DingGroupName record, @Param("example") DingGroupNameExample example);

    int updateByPrimaryKeySelective(DingGroupName record);

    int updateByPrimaryKey(DingGroupName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_group_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DingGroupName> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_group_name
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DingGroupName> list, @Param("selective") DingGroupName.Column ... selective);
}