package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.MessageLog;
import com.dianwoba.dispatch.sender.entity.MessageLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageLogMapper {
    long countByExample(MessageLogExample example);

    int deleteByExample(MessageLogExample example);

    int deleteByPrimaryKey(Long id);

    int insert(MessageLog record);

    int insertSelective(MessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MessageLog> selectByExampleSelective(@Param("example") MessageLogExample example, @Param("selective") MessageLog.Column ... selective);

    List<MessageLog> selectByExample(MessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MessageLog selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MessageLog.Column ... selective);

    MessageLog selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") MessageLog record, @Param("example") MessageLogExample example);

    int updateByExample(@Param("record") MessageLog record, @Param("example") MessageLogExample example);

    int updateByPrimaryKeySelective(MessageLog record);

    int updateByPrimaryKey(MessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<MessageLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<MessageLog> list, @Param("selective") MessageLog.Column ... selective);
}