package com.dianwoba.dispatch.sender.mapper;

import com.dianwoba.dispatch.sender.entity.TokenBucketBackup;
import com.dianwoba.dispatch.sender.entity.TokenBucketBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokenBucketBackupMapper {
    long countByExample(TokenBucketBackupExample example);

    int deleteByExample(TokenBucketBackupExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(TokenBucketBackup record);

    int insertSelective(TokenBucketBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_bucket_backup
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TokenBucketBackup> selectByExampleSelective(@Param("example") TokenBucketBackupExample example, @Param("selective") TokenBucketBackup.Column ... selective);

    List<TokenBucketBackup> selectByExample(TokenBucketBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_bucket_backup
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TokenBucketBackup selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TokenBucketBackup.Column ... selective);

    TokenBucketBackup selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") TokenBucketBackup record, @Param("example") TokenBucketBackupExample example);

    int updateByExample(@Param("record") TokenBucketBackup record, @Param("example") TokenBucketBackupExample example);

    int updateByPrimaryKeySelective(TokenBucketBackup record);

    int updateByPrimaryKey(TokenBucketBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_bucket_backup
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TokenBucketBackup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_bucket_backup
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TokenBucketBackup> list, @Param("selective") TokenBucketBackup.Column ... selective);
}